version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672
    restart: always
  innocence-chi:
    build: .
    ports:
      - 8443:443
      - 5858:5858
    links:
      - rabbitmq
    environment:
      - AMQP=amqp://rabbitmq:5672
    restart: always
  coturn:
    image: instrumentisto/coturn
    ports:
      - 3478:3478
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    restart: always
