version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672
  innocence-chi:
    build: .
    entrypoint: ./entrypoint.sh -d
    volumes:
      - .:/innocchi
    ports:
      - 8443:443
      - 5858:5858
    links:
      - rabbitmq
    environment:
      - AMQP=amqp://rabbitmq:5672
